### ISSUE TITLE
Re-enable Windows CI

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1934]
Tests are failing on Windows in #1920, the issue seems related to \r\n handling of newlines.

I don't have a Windows computer to reproduce so I'm opening this issue here to ask for help to re-enable windows. The following YAML adds a job to run tests on Windows
```
  windows:
    name: Windows tests
    runs-on: windows-latest
    env:
      JAVA_OPTS: -Xss2m -Xmx1024m -XX:-TieredCompilation -XX:ReservedCodeCacheSize=48m -Dfile.encoding=UTF-8 -Djna.nosys=true
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
      - name: sbt ci-windows
        run: |
          rm .jvmopts
          sbt "-Djna.nosys=true" ci-windows
        shell: bash
```
